"""Domain definition for the irregular tissue geometry."""

from dataclasses import dataclass
from typing import Callable

import numpy as np


def _default_lower_boundary(x: float) -> float:
    return max(0.0, 0.2 * np.sin(2.0 * np.pi * x))


def _default_upper_boundary(x: float) -> float:
    del x
    return 1.0


@dataclass(frozen=True)
class Domain:
    """A two-dimensional domain in the unit square with a variable lower boundary.

    The domain is defined for points (x, y) inside the unit square ``[0, 1] x
    [0, 1]`` that lie above a lower boundary curve. The default lower boundary is
    ``max(0.0, 0.2 * np.sin(2.0 * np.pi * x))``, and the default upper boundary is ``y = 1``.
    """

    x_range: tuple[float, float] = (0.0, 1.0)
    upper_boundary: Callable[[float], float] = _default_upper_boundary
    lower_boundary: Callable[[float], float] = _default_lower_boundary

    def contains(self, points: np.ndarray, tol: float = 0.0) -> np.ndarray:
        """Test whether points lie in the closed irregular domain.

        Parameters
        ----------
        points:
            Array whose last dimension stores ``(x, y)`` coordinates.
        tol:
            Nonnegative tolerance added to each boundary comparison. Positive
            values are useful when checking points generated by floating-point
            mesh operations.

        Returns
        -------
        numpy.ndarray
            Boolean mask with the same leading shape as ``points``. ``True``
            marks points inside the Domain.
        """

        x = points[..., 0]
        y = points[..., 1]
        lower = np.vectorize(self.lower_boundary)(x)
        upper = np.vectorize(self.upper_boundary)(x)
        x_min, x_max = self.x_range
        return (
            (x >= x_min - tol)
            & (x <= x_max + tol)
            & (y >= lower - tol)
            & (y <= upper + tol)
        )
